In [1]:
import h5py
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def preprocessing(X, num_components = 50):
    num_features = X.shape[1]
    
    X = X - np.mean(X, axis=0) # centering
    X = X / X.std(axis=0) # standardization

    # PCA
    cov = np.cov(X.T)
    eig_vals, eig_vecs = np.linalg.eig(cov)

    for ev in eig_vecs:
        np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))

    # Make a list of (eigenvalue, eigenvector) tuples
    eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

    # Sort the (eigenvalue, eigenvector) tuples from high to low
    eig_pairs.sort()
    eig_pairs.reverse()

    pca_matrix = eig_pairs[0][1].reshape(num_features, 1)

    for i in range(1, num_components):
        pca_matrix = np.hstack((pca_matrix,
                                eig_pairs[i][1].reshape(num_features, 1)))

    X = X.dot(pca_matrix)

    # Whitening
    X = X / np.sqrt(eig_vals[:num_components])
    
    return X

In [3]:
def calc(x, y):
    return np.sqrt(np.sum(np.power(x - (y / 2), 2)))

***Inception v4***

In [37]:
X_1 = np.load("./embeddings_inception_v4.npy")
X_1 = preprocessing(X_1)

***Inception ResNet v1***

In [38]:
X_2 = np.load("./embeddings.npy")
X_2 = preprocessing(X_2)

In [40]:
current = X_2

loops = 10
means = np.zeros(loops)

count = 0
cnt = 0

lng_data = len(current)

for j in range(loops):
    print("Loop: ", j)
    
    indx = np.random.choice(lng_data, 1000)
    lng = len(indx)
    points = np.zeros(lng)
    
    for i in current[indx]:
        indexes = np.random.choice(lng_data, 1000)

        for k in current[indexes]:
            if calc(i, k) <= (np.linalg.norm(k) / 2):
                count += 1

        points[cnt] = count
        count = 0
        
        cnt += 1
        
    cnt = 0
    means[j] = points.mean()
    print(means)

Loop:  0
[ 0.076  0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
Loop:  1
[ 0.076  0.056  0.     0.     0.     0.     0.     0.     0.     0.   ]
Loop:  2
[ 0.076  0.056  0.086  0.     0.     0.     0.     0.     0.     0.   ]
Loop:  3
[ 0.076  0.056  0.086  0.071  0.     0.     0.     0.     0.     0.   ]
Loop:  4
[ 0.076  0.056  0.086  0.071  0.077  0.     0.     0.     0.     0.   ]
Loop:  5
[ 0.076  0.056  0.086  0.071  0.077  0.067  0.     0.     0.     0.   ]
Loop:  6
[ 0.076  0.056  0.086  0.071  0.077  0.067  0.067  0.     0.     0.   ]
Loop:  7
[ 0.076  0.056  0.086  0.071  0.077  0.067  0.067  0.065  0.     0.   ]
Loop:  8
[ 0.076  0.056  0.086  0.071  0.077  0.067  0.067  0.065  0.068  0.   ]
Loop:  9
[ 0.076  0.056  0.086  0.071  0.077  0.067  0.067  0.065  0.068  0.067]


***Inception v4***

In [39]:
current = X_1

loops = 10
means = np.zeros(loops)

count = 0
cnt = 0

lng_data = len(current)

for j in range(loops):
    print("Loop: ", j)
    
    indx = np.random.choice(lng_data, 1000)
    lng = len(indx)
    points = np.zeros(lng)
    
    for i in current[indx]:
        indexes = np.random.choice(lng_data, 1000)

        for k in current[indexes]:
            if calc(i, k) <= (np.linalg.norm(k) / 2):
                count += 1

        points[cnt] = count
        count = 0
        
        cnt += 1
        
    cnt = 0
    means[j] = points.mean()
    print(means)

Loop:  0
[ 0.125  0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
Loop:  1
[ 0.125  0.137  0.     0.     0.     0.     0.     0.     0.     0.   ]
Loop:  2
[ 0.125  0.137  0.144  0.     0.     0.     0.     0.     0.     0.   ]
Loop:  3
[ 0.125  0.137  0.144  0.127  0.     0.     0.     0.     0.     0.   ]
Loop:  4
[ 0.125  0.137  0.144  0.127  0.097  0.     0.     0.     0.     0.   ]
Loop:  5
[ 0.125  0.137  0.144  0.127  0.097  0.133  0.     0.     0.     0.   ]
Loop:  6
[ 0.125  0.137  0.144  0.127  0.097  0.133  0.117  0.     0.     0.   ]
Loop:  7
[ 0.125  0.137  0.144  0.127  0.097  0.133  0.117  0.153  0.     0.   ]
Loop:  8
[ 0.125  0.137  0.144  0.127  0.097  0.133  0.117  0.153  0.157  0.   ]
Loop:  9
[ 0.125  0.137  0.144  0.127  0.097  0.133  0.117  0.153  0.157  0.109]


***Resnet v2***

In [29]:
X_3 = np.load("./embeddings_resnet_v2_152.npy")
X_3 = preprocessing(X_3)

In [35]:
current = X_3

loops = 10
means = np.zeros(loops)

count = 0
cnt = 0

lng_data = len(current)

for j in range(loops):
    print("Loop: ", j)
    
    indx = np.random.choice(lng_data, 1000)
    lng = len(indx)
    points = np.zeros(lng)
    
    for i in current[indx]:
        indexes = np.random.choice(lng_data, 1000)

        for k in current[indexes]:
            if calc(i, k) <= (np.linalg.norm(k) / 2):
                count += 1

        points[cnt] = count
        count = 0
        
        cnt += 1
        
    cnt = 0
    means[j] = points.mean()
    print(means)

Loop:  0
[ 0.274  0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
Loop:  1
[ 0.274  0.249  0.     0.     0.     0.     0.     0.     0.     0.   ]
Loop:  2
[ 0.274  0.249  0.258  0.     0.     0.     0.     0.     0.     0.   ]
Loop:  3
[ 0.274  0.249  0.258  0.242  0.     0.     0.     0.     0.     0.   ]
Loop:  4
[ 0.274  0.249  0.258  0.242  0.267  0.     0.     0.     0.     0.   ]
Loop:  5
[ 0.274  0.249  0.258  0.242  0.267  0.231  0.     0.     0.     0.   ]
Loop:  6
[ 0.274  0.249  0.258  0.242  0.267  0.231  0.229  0.     0.     0.   ]
Loop:  7
[ 0.274  0.249  0.258  0.242  0.267  0.231  0.229  0.247  0.     0.   ]
Loop:  8
[ 0.274  0.249  0.258  0.242  0.267  0.231  0.229  0.247  0.229  0.   ]
Loop:  9
[ 0.274  0.249  0.258  0.242  0.267  0.231  0.229  0.247  0.229  0.222]
